baseURL = 'https://2fd5.com/'
languageCode = 'en-us'
title = '2fd5.com Site'
theme = 'coming-soon'

[params]
    title = "2fd5.com - 'Empathy Guide' - Coming Soon"
    description = "Welcome to our unique hub, home to custom GPT models like the 'Empathy Guide.'"
    favicon = ""
    message = "COMING SOON!" 
    release = "Jan 30, 2024" 
    background = "" 

socialIcons = [
    {name = "email", url = "magic@2fd5.com"},
    {name = "twitter", url = "https://x.com/2fd5_com"},
    {name = "github", url = "https://github.com/2fd5"},
]
